"""Create temporary stub source files for missing documents in Sphinx toctrees.

Add ``toctree_missing_pages`` to ``extensions`` in conf.py. The title and body
may use Python mapping substitutions such as ``%(path)s``. The path is
root-relative, starts with ``/``, and has no source-file suffix.

Missing toctree entries are redirected in memory to sibling ``-stub`` pages.
The original source files are not modified. Stub files are removed at
build-finished; if a build is interrupted, marked leftovers are refreshed or
removed on the next build. This handles absent source files, not errors reading
existing but unreadable files.
"""

from __future__ import annotations

import re
from pathlib import Path

_MARKER = ".. generated by toctree_missing_pages; do not edit"
_TOCTREE = re.compile(r"^(\s*)\.\.\s+toctree::\s*(?:#.*)?$")
_EXPLICIT_TITLE = re.compile(r"^.*?<([^<>]+)>\s*$")


def _source_suffixes(app):
    suffixes = app.config.source_suffix
    if isinstance(suffixes, dict):
        return tuple(suffixes)
    if isinstance(suffixes, str):
        return (suffixes,)
    return tuple(suffixes)


def _toctree_entries(path):
    """Yield (line number, literal document entry) pairs from toctrees."""
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError):
        return

    i = 0
    while i < len(lines):
        match = _TOCTREE.match(lines[i])
        if not match:
            i += 1
            continue

        directive_indent = len(match.group(1))
        i += 1
        while i < len(lines):
            line = lines[i]
            if line.strip() and len(line) - len(line.lstrip()) <= directive_indent:
                break
            i += 1

            entry = line.strip()
            if not entry or entry.startswith(":") or entry.startswith(".."):
                continue

            title_match = _EXPLICIT_TITLE.match(entry)
            if title_match:
                entry = title_match.group(1).strip()

            if "://" in entry or entry == "self" or any(c in entry for c in "*?[]"):
                continue

            # i has already advanced past this line.
            yield i - 1, entry


def _entry_path(entry, parent_docname):
    entry = entry.split("#", 1)[0].strip()
    if not entry:
        return None

    # A leading slash in a toctree entry means relative to the source root.
    if entry.startswith("/"):
        relative = Path(entry.lstrip("/"))
    else:
        relative = Path(parent_docname).parent / entry

    if ".." in relative.parts:
        return None
    return relative


def _stub_entry_line(line):
    """Return a toctree line whose target points to the sibling -stub page."""
    newline = line[len(line.rstrip("\r\n")) :]
    content = line[: len(line) - len(newline)]
    indent = content[: len(content) - len(content.lstrip())]
    entry = content.strip()

    title_match = _EXPLICIT_TITLE.match(entry)
    if title_match:
        target = title_match.group(1).strip()
        target_start, target_end = title_match.span(1)
    else:
        target = entry
        target_start, target_end = 0, len(entry)

    target_path, separator, fragment = target.partition("#")
    path = Path(target_path)
    if path.suffix:
        path = path.with_suffix("")
    stub_target = path.with_name(path.name + "-stub").as_posix()
    if separator:
        stub_target += separator + fragment

    rewritten_entry = (
        entry[:target_start] + stub_target + entry[target_end:]
    )
    return indent + rewritten_entry + newline


def _is_generated(path):
    try:
        with path.open("r", encoding="utf-8") as source:
            return source.readline().rstrip("\r\n") == _MARKER
    except (OSError, UnicodeError):
        return False


def _stub_text(app, docname):
    path = "/" + docname.lstrip("/")
    substitutions = {"path": path}

    title = app.config.toctree_missing_title % substitutions
    body = app.config.toctree_missing_body % substitutions
    # Keep compatibility with the earlier {docname} body placeholder.
    body = body.replace("{docname}", docname)

    return f"{_MARKER}\n\n{title}\n{'=' * len(title)}\n\n{body.rstrip()}\n"


def _source_read(app, docname, source):
    """Redirect missing toctree entries to their generated stub pages."""
    rewrites = getattr(app, "_toctree_missing_rewrites", {}).get(docname)
    if not rewrites:
        return

    lines = source[0].splitlines(keepends=True)
    for line_number, replacement in rewrites.items():
        if line_number < len(lines):
            lines[line_number] = replacement
    source[0] = "".join(lines)


def _prepare_stubs(app, config):
    srcdir = Path(app.srcdir)
    suffixes = _source_suffixes(app)
    generated = set()
    rewrites = {}

    for source in srcdir.rglob("*"):
        if not source.is_file() or source.suffix not in suffixes:
            continue

        parent_docname = source.relative_to(srcdir).with_suffix("").as_posix()
        try:
            source_lines = source.read_text(encoding="utf-8").splitlines(
                keepends=True
            )
        except (OSError, UnicodeError):
            continue

        for line_number, entry in _toctree_entries(source):
            relative = _entry_path(entry, parent_docname)
            if relative is None:
                continue

            # Find the original target using the same rules as before.
            if relative.suffix:
                candidates = [srcdir / relative]
                original_base = relative.with_suffix("")
                stub_suffixes = (relative.suffix,)
            else:
                candidates = [
                    srcdir / relative.with_suffix(suffix) for suffix in suffixes
                ]
                if not candidates:
                    candidates = [srcdir / relative.with_suffix(".rst")]
                original_base = relative
                stub_suffixes = suffixes or (".rst",)

            # Remove leftover generated original-name stubs from older builds.
            for candidate in candidates:
                if candidate.exists() and _is_generated(candidate):
                    candidate.unlink()

            # A real original page always wins; leave its toctree entry alone.
            if any(candidate.exists() for candidate in candidates):
                continue

            stub_base = original_base.with_name(original_base.name + "-stub")
            stub_candidates = [
                srcdir / stub_base.with_suffix(suffix) for suffix in stub_suffixes
            ]

            # Refresh leftovers from an interrupted build, but never overwrite a
            # user-authored file with the same -stub name.
            for candidate in stub_candidates:
                if candidate.exists() and _is_generated(candidate):
                    candidate.unlink()

            if not any(candidate.exists() for candidate in stub_candidates):
                target = stub_candidates[0]
                stub_docname = stub_base.as_posix()
                try:
                    target.parent.mkdir(parents=True, exist_ok=True)
                    # Keep %(path)s and {docname} referring to the missing page,
                    # not to the implementation-detail -stub name.
                    original_docname = original_base.as_posix()
                    target.write_text(
                        _stub_text(app, original_docname), encoding="utf-8"
                    )
                except OSError:
                    continue
                generated.add(target)

            # Rewrite only this toctree entry, preserving its title and fragment.
            if line_number < len(source_lines):
                rewrites.setdefault(parent_docname, {})[line_number] = (
                    _stub_entry_line(source_lines[line_number])
                )

    app._toctree_missing_generated = generated
    app._toctree_missing_rewrites = rewrites


def _cleanup_stubs(app, exception):
    for path in getattr(app, "_toctree_missing_generated", ()):
        try:
            if _is_generated(path):
                path.unlink()
        except OSError:
            pass


def setup(app):
    app.add_config_value(
        "toctree_missing_title", "%(path)s (stub)", "env", types=[str]
    )
    app.add_config_value(
        "toctree_missing_body",
        "This page is not available in this build.",
        "env",
        types=[str],
    )
    app.connect("config-inited", _prepare_stubs)
    app.connect("source-read", _source_read)
    app.connect("build-finished", _cleanup_stubs)
    return {
        "version": "1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
